### ISSUE TITLE
Configure staging: multiple analyzers, multiple repositories

### ISSUE THREAD

**Issue by bzz** [src-d/lookout#140]
For successful internal dog-fooding as well and user research, as soon as https://github.com/src-d/issues-infrastructure/issues/213 is finished, staging deployment should produce some meaningful results on number of repositories using some number of analysers for different languages.

Repositories to run on:
 - [x] src-d/lookout (Golang)
 - [x] ? [bblfsh/uast-viewer](https://github.com/bblfsh/uast-viewer) (JavaScript)
 - [x] ? [src-d/siva-java](https://github.com/src-d/siva-java) (Java)

Analyzers:
 - [x] src-d/lookout dummy ~#138~
 - [x] [src-d/style-analyzer](https://github.com/src-d/style-analyzer) (JavaScript) ~https://github.com/src-d/style-analyzer/issues/30~
 - [x] src-d/lookout gometalint (Golang) #136 
 - [x] analyzer based [bblfsh/sonar-checks](https://github.com/bblfsh/sonar-checks) (Java)
         https://github.com/src-d/lookout-sonarcheck-analyzer/

**Comment by bzz** [comment]
[lookout-gometalint-analyzer](https://github.com/bzz/lookout-gometalint-analyzer/) temporary deployed on staging using

```
kubectl apply -f ./gometalint-analyzer.yml
```

**Comment by bzz** [comment]
https://github.com/src-d/lookout-sonarcheck-analyzer/releases/tag/v0.0.1 deployed on staging using

```
kubectl apply -f ./sonarcheck-analyzer.yml
```

**Comment by bzz** [comment]
The only things left here is 
 - [ ] installing https://github.com/apps/lookout-staging on siva-java and  
 - [ ] https://github.com/src-d/lookout/pull/291

**Comment by bzz** [comment]
Installation of Gh App on siva-java repo was requested though https://github.com/apps/lookout-staging, now I guess that org admin have to "approve" it somehow \cc @rporres @meyskens

**Comment by rporres** [comment]
taking a look, @bzz

**Comment by rporres** [comment]
Can you comment, @mcuadros?

**Comment by bzz** [comment]
I think the App has been now transferd to src-d ownership, and from what I can tell - it's installed on siva-java repo.

🎉
