### ISSUE TITLE
Configurable Analyzers

### ISSUE THREAD

**Issue by bzz** [src-d/lookout#20]
- [x] add support for multiple Analyzers in lookout server 
  - [x] read per-repository configuration with DataServer API `GetFiles({IncludePattern: "^\.lookout\.yml$"})` #55 
  - [x] hard-code static global configuration of the server
  - [x] merged global and repo-specific configurations #71
  - [x] pass configuration to each individual Analyzer in `NotifyReview` gRPC  #55

**Comment by smacker** [comment]
> add support for multiple Analyzers in lookout server

Should analyzers be defined in some config file or using flags/env vars as we do right now?

**Comment by bzz** [comment]
As we discussion, Analyzers should be configurable with the same options either 
 - from `.lookout.yml`
 - from server side

On the server side, this issue just includes `hard-code static global configuration of the server`, leaving the details of how to load this configuration for later.

That way, loading it from a file can be handled in separate issue.

**Comment by smacker** [comment]
Okay. Thanks! That means we most probably need to remove current flag/env for an analyzer in the server.

**Comment by smacker** [comment]
> merged global and repo-specific configurations

how exactly do we want to do that? What should be merged and what should be replaced?

**Comment by bzz** [comment]
From discussion elsewhere:

Global config
```analyzers:
  - name: Dummy
    addr: ipv4://localhost:10302
    settings:
      key1: 1
      key2: [1,2]
      key3:
       subkey1: 1
       subkey2: [1, 2]
       subkey3:
        subsubkey: 1```


repo config:
```analyzers:
  - name: Dummy
    settings:
      key2: [5]
      key3:
       subkey1: 3
       subkey3:
        subsubkey2: 2
       subkey4: 4
```

would result in merged 

```
analyzers:
  - name: Dummy
    addr: ipv4://localhost:10302
    settings:
      key1: 1
      key2: [5]
      key3:
       subkey1: 3
       subkey2: [1, 2]
       subkey3:
        subsubkey: 1
        subsubkey2: 2
       subkey4: 4
```
