### ISSUE TITLE
[SDK] Make user experience more like curl

### ISSUE THREAD

**Issue by bzz** [src-d/lookout#29]
Improve user experience of lookout SDK

 0. [x] add `-v` to push/review commands, to hide debug details (i.e all nifty gRPC)  #37
 1. [x] If no bblfsh service available, show just 1 warning that no UASTs will be available and trigger analyzer #34
     Right now it prints lots of logs and takes ~3 sec
 2. [x] if no analyzer running - just print 1 line of warning and stop (same as cURL) #34
     Right now it attempts to re-connect \w lots of verbose logs

**Comment by smacker** [comment]
During code review, we found more ideas for improvements. They are tracked in separated issues.
