### ISSUE TITLE
Set a default config file for each organization

### ISSUE THREAD

**Issue by carlosms** [src-d/lookout#401]
Depends on #400.
This issue is to be able to define a default `lookout.yml` for all the repositories (current and future) of an organization.

To do this we'll need:
- [x] New table to store the config file contents for each organization #483
- [x] Endpoint to perform the update. A user should only be able to change the org config file it they are an admin of the organization. #484
- [x] UI should be simple. A textarea where you can paste the yaml contents will be enough for now. #484
- [x] The default config will be merged with the `lookout.yml` commited in the repository. In this case the one in the repository has priority over the organization default. #493
